//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarathonSkills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class donations
    {
        public int donation_id { get; set; }
        public int donation_amount { get; set; }
        public string donator_firstname { get; set; }
        public string donator_lastname { get; set; }
        public string donator_othername { get; set; }
        public int runner_id { get; set; }
    
        public virtual runners runners { get; set; }
    }
}
