//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarathonSkills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class event_registration
    {
        public int event_registration_id { get; set; }
        public int event_id { get; set; }
        public int runner_id { get; set; }
        public System.DateTime registration_datetime { get; set; }
    
        public virtual events events { get; set; }
        public virtual runners runners { get; set; }
    }
}
