//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarathonSkills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class event_reviews
    {
        public int event_review_id { get; set; }
        public int user_id { get; set; }
        public int event_id { get; set; }
        public int event_review_mark { get; set; }
        public string event_review_description { get; set; }
        public System.DateTime event_review_date { get; set; }
    
        public virtual events events { get; set; }
        public virtual users users { get; set; }
    }
}
