//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarathonSkills.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MarathonEntities : DbContext
    {
        public MarathonEntities()
            : base("name=MarathonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<charities> charities { get; set; }
        public virtual DbSet<countries> countries { get; set; }
        public virtual DbSet<donations> donations { get; set; }
        public virtual DbSet<event_registration> event_registration { get; set; }
        public virtual DbSet<event_results> event_results { get; set; }
        public virtual DbSet<event_types> event_types { get; set; }
        public virtual DbSet<events> events { get; set; }
        public virtual DbSet<genders> genders { get; set; }
        public virtual DbSet<marathons> marathons { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<runners> runners { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<volunteers> volunteers { get; set; }
        public virtual DbSet<event_reviews> event_reviews { get; set; }
    }
}
