//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarathonSkills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class volunteers
    {
        public int volunteer_id { get; set; }
        public string volunteer_firstname { get; set; }
        public string volunteer_lastname { get; set; }
        public string volunteer_othername { get; set; }
        public System.DateTime volunteer_birthdate { get; set; }
        public int country_id { get; set; }
        public string gender_code { get; set; }
    
        public virtual countries countries { get; set; }
        public virtual genders genders { get; set; }
    }
}
